name: PyTest

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov codecov
        pip install -r requirements.txt

    - name: Run tests
      run: pytest --cov=web --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3